version: '3.9-buster'
networks:
  app_network:
    driver: bridge

services:
  flask-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: sourav299/flask-app-with-mongodb:01
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=d
      - MONGO_URI=mongodb://root:example@mongo:27017/userdata?authSource=admin
      - SECRET_KEY=your_secret_key
    depends_on:
      - mongo
    networks:
      - app_network

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app_network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - app_network

volumes:
  mongo_data:

    


